# -*- coding: utf-8 -*-
"""MF_Thets_step3_Merge_Vecs_After_Bert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lxhaYmlmER6vhlVcNezyY5dOZQ2X3Cor
"""

import numpy as np

from google.colab import files
uploaded = files.upload()

a1=np.load('plot_vec_Genres_director_title_after_Bert_60 (1).npy',allow_pickle=True)

from google.colab import files
uploaded = files.upload()

a2=np.load('plot_vec_Genres_director_title_after_Bert_1620.npy',allow_pickle=True)

a1=np.concatenate((a1,a2),axis=0)

print(a1.shape)

np.save('plot_vec_Genres_director_title_1682_768.npy',a1)
from google.colab import files
files.download('plot_vec_Genres_director_title_1682_768.npy')

from google.colab import files
files.download('plot_vec_Genres_director_title_1682_768.npy')